// Copyright 2020-2021 David Colson. All rights reserved.

#include "Vec2.h"

#include "TypeSystem/TypeDatabase.h"

REFLECT_TEMPLATED_BEGIN(Vec2f)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_END()

REFLECT_TEMPLATED_BEGIN(Vec2d)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_END()

REFLECT_TEMPLATED_BEGIN(Vec2i)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_END()